# Generated by Django 6.0.5 on 2026-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_fecha_pago_perfil_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='mercadopago_payment_id',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_pago',
        ),
    ]
