# Generated by Django 6.0.5 on 2026-05-12 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('abierta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
                ('visitante', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=10)),
                ('resultado_real', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jornada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiniela.jornada')),
            ],
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seleccion', models.CharField(max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.partido')),
            ],
        ),
    ]
