# Generated by Django 6.0.5 on 2026-05-12 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronostico',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pronostico',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pronostico',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
