# Generated by Django 6.0.5 on 2026-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0002_remove_pronostico_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha_partido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora_partido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='pais_sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
