# Generated by Django 6.0.5 on 2026-07-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiniela', '0005_asignar_torneo_mundial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiniela.torneo'),
        ),
    ]
